spring.application.name=call-center-system

# Spring Boot Veritabani Ayarlari (SQL Server Authentication)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=call_center_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12@w34er
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA Ayarlari
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
